extractors:
  depth: promptda
  normals: metric3dv2-normals
  promptda:
    pretrained_path: /root/autodl-tmp/PriMo/local/weights/prompt_depth_anything_vitl.ckpt
    prompt_depth_dir: /root/autodl-tmp/PriMo/local/example/sofa/depth
reconstruction:
  image:
    depth:
      depth_uncertainty: 0.079
      prior_uncertainty: false
