extractors:
  depth: promptda
  normals: metric3dv2-normals
  # Per-model overrides for promptda
  promptda:
    depth_png_dir: /root/autodl-tmp/mpsfm/local/example/97/depth
    pattern_depth: "{stem}.png"
    scale: 1

reconstruction:
  image:
    depth:
      # PromptDA does not provide depth_variance
      prior_uncertainty: false
      # Tune based on your depth noise level
      depth_uncertainty: 0.079                       

registration:
  use_prior_poses: true  # 启用先验外参
  pose_config_path: "/root/autodl-tmp/mpsfm/local/example/camera_poses.yaml"  # 外参配置文件路径